Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.hostname = "python-test"
  config.vm.network :forwarded_port, guest: 5000, host: 5000
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
  end
  config.vm.provision "docker", run: 'always' do |d|
    d.post_install_provision "shell", inline:"docker image rm -f roeezab/exam-python:latest || echo"
    d.run "roeezab/exam-python", args: "-p 5000:5000"
  end
end
